[package]
name = "paymsg-validate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
paymsg-core = { workspace = true }
paymsg-mt = { workspace = true }
paymsg-iso20022 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
